# Generated by Django 2.0.1 on 2018-02-04 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(max_length=80, verbose_name='Nombres')),
                ('primerApellido', models.TextField(max_length=80, verbose_name='Primer Apellido')),
                ('segundoApellido', models.TextField(max_length=80, verbose_name='Segundo Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cédula de Extranjeria'), ('PA', 'Pasaaporte'), ('TI', 'Tarjeta de Identidad')], max_length=2, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=11, verbose_name='Numero de Documento')),
                ('telefono', models.TextField(max_length=80, verbose_name='telefono de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('direccion', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Municipio')),
            ],
        ),
    ]
