# Generated by Django 2.0.1 on 2018-02-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestador',
            options={'verbose_name_plural': 'prestadores'},
        ),
    ]
