# Generated by Django 2.0.1 on 2018-04-01 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('prestadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='servicios',
            field=models.ManyToManyField(to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestadores', to=settings.AUTH_USER_MODEL),
        ),
    ]
