# Generated by Django 2.0.1 on 2018-05-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20180504_1433'),
        ('prestadores', '0002_auto_20180419_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='zona',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='servicios.Zona'),
        ),
    ]
