# Generated by Django 2.0.1 on 2018-02-07 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestadores', '0002_auto_20180204_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestadores', to=settings.AUTH_USER_MODEL),
        ),
    ]
