# Generated by Django 2.0.1 on 2018-04-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0002_auto_20180331_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('disponibiliad', models.BooleanField()),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestadores.Prestador')),
            ],
        ),
    ]
