# Generated by Django 2.0.1 on 2018-04-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0003_disponibilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilidad',
            old_name='disponibiliad',
            new_name='disponibilidad',
        ),
    ]
