# Generated by Django 2.0.1 on 2018-06-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0003_prestador_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='servicios',
        ),
    ]
