# Generated by Django 2.0.1 on 2018-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_compra_mediopago'),
        ('prestadores', '0003_prestador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='servicios',
            field=models.ManyToManyField(to='servicios.Servicio'),
        ),
    ]
