# Generated by Django 2.0.1 on 2018-03-02 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0004_prestador_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestador',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
