# Generated by Django 2.0.1 on 2018-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0006_auto_20180302_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='calificacion',
            field=models.CharField(max_length=2, null=True, verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='imagePath',
            field=models.FileField(null=True, upload_to='media/prestadores'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='insignia',
            field=models.CharField(max_length=2, null=True, verbose_name='Insignia'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='perfil',
            field=models.TextField(max_length=300, null=True, verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='profesion',
            field=models.CharField(max_length=56, null=True, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='nombres',
            field=models.CharField(max_length=80, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='primerApellido',
            field=models.CharField(max_length=80, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='segundoApellido',
            field=models.CharField(max_length=80, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='telefono',
            field=models.CharField(max_length=80, verbose_name='telefono de contacto'),
        ),
    ]
