# Generated by Django 2.0.1 on 2018-06-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_auto_20180626_2216'),
        ('prestadores', '0008_auto_20180628_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestadorSericio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('prestador', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestador_servicio', to='prestadores.Prestador')),
                ('servicios', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_prestador', to='servicios.Servicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='prestadorserivio',
            name='prestador',
        ),
        migrations.RemoveField(
            model_name='prestadorserivio',
            name='servicios',
        ),
        migrations.DeleteModel(
            name='PrestadorSerivio',
        ),
    ]
