# Generated by Django 2.0.1 on 2018-06-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_auto_20180626_2216'),
        ('prestadores', '0009_auto_20180628_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrestadorSericio',
            new_name='PrestadorServicio',
        ),
    ]
