# Generated by Django 2.0.1 on 2018-06-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0012_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='prestador',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudios', to='prestadores.Prestador'),
        ),
    ]
