# Generated by Django 2.0.1 on 2018-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0017_auto_20180704_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='archivoPath',
            field=models.FileField(null=True, upload_to='prestadores', verbose_name='Archivo'),
        ),
    ]
