# Generated by Django 2.0.1 on 2018-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0018_formacion_archivopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacion',
            name='archivoPath',
            field=models.FileField(null=True, upload_to='prestadores/formacion', verbose_name='Archivo'),
        ),
    ]
