#TIPOS DE DOCUMENTO

CEDULA_CIUDADANIA = 'CC'
CEDULA_EXTRANJERIA = 'CE'
PASAPORTE = 'PA'
TARJETA_IDENTIDAD = 'TI'

TIPO_DOCUMENTO_CHOICES = (

    (CEDULA_CIUDADANIA, 'Cedula de Ciudadania'),
    (CEDULA_EXTRANJERIA, 'Cédula de Extranjeria'),
    (PASAPORTE, 'Pasaaporte'),
    (TARJETA_IDENTIDAD, 'Tarjeta de Identidad')

)

MASCULINO = 'M'
FEMENINO = 'F'
SEXO_CHOICES = (
    (MASCULINO,'Masculino'),
    (FEMENINO , "Femenino")
)

# TARJETAS DE CREDITO

TARJETA_CREDITO = 'TC'

MEDIOS_DE_PAGO_CHOICES = (
    (TARJETA_CREDITO, 'Tarjeta de credito'),
)

# FRANQUICIAS

FRANQUICIA_MASTER_CARD = "FMC"
FRANQUICIA_AMERICAN_EXPRESS = "FAE"
FRANQUICIA_VISA = "FVI"
FRANQUICIA_DINNERS_CLUB = "FDC"

FRANQUICIAS_CHOICES = (
    (FRANQUICIA_MASTER_CARD, "MASTER CARD"),
    (FRANQUICIA_AMERICAN_EXPRESS, "AMERICAN EXPRESS"),
    (FRANQUICIA_VISA, "VISA"),
    (FRANQUICIA_DINNERS_CLUB, "DINNERS CLUB")
)
