# Generated by Django 2.0.1 on 2018-04-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestadores', '0001_initial'),
        ('parametrizacion', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('detalle', models.CharField(max_length=150)),
                ('imagePath', models.FileField(upload_to='media/categorias')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.EstadoCompra')),
                ('medioPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.TipoMedioPago')),
            ],
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadDeSesiones', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('detalle', models.CharField(max_length=150)),
                ('valor', models.FloatField()),
                ('sesionEjecutada', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compraDetalles', to='servicios.Compra')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.EstadoCompraDetalle')),
            ],
            options={
                'verbose_name_plural': 'CompraDetalles',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opiniones', to='clientes.Cliente')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opiniones', to='prestadores.Prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('detalle', models.CharField(max_length=150)),
                ('cantidadDeSesiones', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valor', models.FloatField()),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='prestadores.Prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('detalle', models.CharField(max_length=150)),
                ('imagePath', models.FileField(upload_to='media/servicios')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.Categoria', verbose_name='Categoria del servicio')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opiniones', to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquete', to='servicios.Paquete'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prestadores.Prestador'),
        ),
    ]
