# Generated by Django 2.0.1 on 2018-04-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetalle',
            old_name='sesionPorAgendadar',
            new_name='sesionPorAgendar',
        ),
    ]
