# Generated by Django 2.0.1 on 2018-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20180420_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='sesionPorAgendar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
