# Generated by Django 2.0.1 on 2018-03-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20180212_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='servicios.Paquete'),
        ),
    ]
