# Generated by Django 2.0.1 on 2018-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20180425_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='sesionPorAgendar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
