# Generated by Django 2.0.1 on 2018-03-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20180302_0935'),
        ('servicios', '0004_auto_20180301_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='medioPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clientes.MedioDePago'),
            preserve_default=False,
        ),
    ]
