# Generated by Django 2.0.1 on 2018-03-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0005_auto_20180302_1508'),
        ('clientes', '0014_auto_20180302_1508'),
        ('servicios', '0005_compra_mediopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opiniones', to='clientes.Cliente')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opiniones', to='prestadores.Prestador')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opiniones', to='servicios.Servicio')),
            ],
        ),
    ]
