# Generated by Django 2.0.1 on 2018-03-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
