# Generated by Django 2.0.1 on 2018-05-04 14:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20180430_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='color',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
