# Generated by Django 2.0.1 on 2018-04-01 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20180401_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.Compra'),
        ),
    ]
