# Generated by Django 2.0.1 on 2018-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_zona_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
