# Generated by Django 2.0.1 on 2018-05-08 13:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20180504_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='zona',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
