# Generated by Django 2.0.1 on 2018-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_compradetalle_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetallesesion',
            name='fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='compradetallesesion',
            name='inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
