# Generated by Django 2.0.1 on 2018-04-01 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20180401_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadoCompraDetalle', to='parametrizacion.EstadoCompraDetalle'),
        ),
    ]
