# Generated by Django 2.0.1 on 2018-04-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_auto_20180401_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compradetalle',
            name='sesionEjecutada',
        ),
    ]
