# Generated by Django 2.0.1 on 2018-06-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0003_prestador_zona'),
        ('servicios', '0010_auto_20180613_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDetalleSesionNovedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novedad', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('CompraDetalleSesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compradetallesesionnovedad', to='servicios.CompraDetalleSesion')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestadornovedad', to='prestadores.Prestador')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
