# Generated by Django 2.0.1 on 2018-04-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0002_estadocompradetallesesion'),
        ('servicios', '0011_remove_compradetalle_sesionejecutada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDetalleSesiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('titulo', models.CharField(default='Sin Titulo', max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=21)),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=21)),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CompraDetalles',
            },
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='sesionAgendadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='sesionFinalizadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compradetallesesiones',
            name='compraDetalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compradetallesesiones', to='servicios.CompraDetalle'),
        ),
        migrations.AddField(
            model_name='compradetallesesiones',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadoCompraDetalleSesiones', to='parametrizacion.EstadoCompraDetalleSesion'),
        ),
    ]
