# Generated by Django 2.0.1 on 2018-06-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_compradetallesesionnovedad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetallesesionnovedad',
            old_name='CompraDetalleSesion',
            new_name='compraDetalleSesion',
        ),
    ]
