# Generated by Django 2.0.1 on 2018-04-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0002_estadocompradetallesesion'),
        ('servicios', '0012_auto_20180409_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompraDetalleSesiones',
            new_name='CompraDetalleSesion',
        ),
        migrations.AlterModelOptions(
            name='compradetallesesion',
            options={'verbose_name_plural': 'CompraDetallesSesiones'},
        ),
    ]
