# Generated by Django 2.0.1 on 2018-07-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_auto_20180626_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='prestador',
        ),
    ]
