# Generated by Django 2.0.1 on 2018-07-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_remove_paquete_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compraDetalle_paquete', to='servicios.Paquete'),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compraDetalle_prestador', to='prestadores.Prestador'),
        ),
    ]
