# Generated by Django 2.0.1 on 2018-04-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_auto_20180409_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetallesesion',
            name='calificacion',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compradetallesesion',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
