# Generated by Django 2.0.1 on 2018-04-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_auto_20180409_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetallesesion',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compradetallesesion',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compradetallesesion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='compradetallesesion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='compradetallesesion',
            name='titulo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
