# Generated by Django 2.0.1 on 2018-07-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_auto_20180703_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='valor',
        ),
    ]
