# Generated by Django 2.0.1 on 2018-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_remove_paquete_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagePath',
            field=models.FileField(upload_to='categorias'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagePath',
            field=models.FileField(upload_to='servicios'),
        ),
    ]
