# Generated by Django 2.0.1 on 2018-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0017_compradetalle_sesionporagendadar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetallesesion',
            old_name='fecha',
            new_name='fechaFin',
        ),
        migrations.AddField(
            model_name='compradetallesesion',
            name='comentario',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='compradetallesesion',
            name='fechaInicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='sesionAgendadas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='sesionFinalizadas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='sesionPorAgendadar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
