# Generated by Django 2.0.1 on 2018-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0018_auto_20180411_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetallesesion',
            name='comentario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
