# Generated by Django 2.0.1 on 2018-07-10 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrizacion', '0001_initial'),
        ('servicios', '0018_auto_20180706_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDetalleHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('compraDetalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compraDetalleSesionesHistorico', to='servicios.CompraDetalle')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadoDetalleSesionesHistorico', to='parametrizacion.EstadoCompraDetalle')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioCompraDetalleSesionesHistorico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CompraDetalleSesionHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('compraDetalleSesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compraDetalleSesionHistorico', to='servicios.CompraDetalleSesion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadoCompraDetalleSesionesHistorico', to='parametrizacion.EstadoCompraDetalleSesion')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioDetalleSesionHistorico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CompraHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compraHistorico', to='servicios.Compra')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EstadoCompraHistorico', to='parametrizacion.EstadoCompra')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioCompraHistorico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
