# Generated by Django 2.0.1 on 2018-07-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_compradetallehistorico_compradetallesesionhistorico_comprahistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetallesesionhistorico',
            name='nombreCompleto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
