# Generated by Django 2.0.1 on 2018-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_auto_20180411_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetallesesion',
            name='comentario',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
