# Generated by Django 2.0.1 on 2018-07-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0020_compradetallesesionhistorico_nombrecompleto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetallesesionhistorico',
            old_name='user',
            new_name='usuario',
        ),
    ]
