# Generated by Django 2.0.1 on 2018-04-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0020_auto_20180412_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='duracionSesion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
