# Generated by Django 2.0.1 on 2018-07-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_auto_20180710_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetallehistorico',
            old_name='user',
            new_name='usuario',
        ),
    ]
