# Generated by Django 2.0.1 on 2018-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0021_paquete_duracionsesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='duracionSesion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
