# Generated by Django 2.0.1 on 2018-07-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0022_auto_20180710_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetallehistorico',
            name='nombreCompleto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
