# Generated by Django 2.0.1 on 2018-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0023_compradetallehistorico_nombrecompleto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprahistorico',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='comprahistorico',
            name='nombreCompleto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
