# Generated by Django 2.0.1 on 2018-07-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0024_auto_20180710_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprahistorico',
            old_name='usuario',
            new_name='usuarior',
        ),
    ]
