# Generated by Django 2.0.1 on 2018-07-10 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0026_remove_comprahistorico_usuarior'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprahistorico',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='usuarioCompraHistorico', to=settings.AUTH_USER_MODEL),
        ),
    ]
