# Generated by Django 2.0.1 on 2018-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0029_auto_20180710_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradetallehistorico',
            old_name='nombreCompleto',
            new_name='usuarioNombreCompleto',
        ),
        migrations.AddField(
            model_name='compradetallehistorico',
            name='estadoNombre',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
