# Generated by Django 2.0.1 on 2018-07-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0030_auto_20180710_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='motivoCancelacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
