# Generated by Django 2.0.1 on 2018-07-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0031_compradetalle_motivocancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
