# Generated by Django 2.0.1 on 2018-07-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0034_remove_chat_compradetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
