# Generated by Django 2.0.1 on 2018-07-22 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0036_chat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='SesionChat',
        ),
    ]
