# Generated by Django 2.0.1 on 2018-08-07 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0039_auto_20180807_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDetalleChatMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paquetechatmensaje',
            name='paqueteChat',
        ),
        migrations.RemoveField(
            model_name='paquetechatmensaje',
            name='usuario',
        ),
        migrations.RenameModel(
            old_name='PaqueteChat',
            new_name='CompraDetalleChat',
        ),
        migrations.DeleteModel(
            name='PaqueteChatMensaje',
        ),
        migrations.AddField(
            model_name='compradetallechatmensaje',
            name='compraDetalleChat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensaje', to='servicios.CompraDetalleChat'),
        ),
        migrations.AddField(
            model_name='compradetallechatmensaje',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='chatUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
