# Generated by Django 2.0.1 on 2018-08-07 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0040_auto_20180807_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetallechat',
            name='compraDetalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat', to='servicios.CompraDetalle'),
        ),
    ]
