# Generated by Django 2.0.1 on 2018-08-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0041_auto_20180807_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetallechatmensaje',
            name='compraDetalleChat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chatmensaje', to='servicios.CompraDetalleChat'),
        ),
    ]
