# Generated by Django 2.0.1 on 2018-04-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80, null=True, verbose_name='Nombres')),
                ('primerApellido', models.CharField(max_length=80, null=True, verbose_name='Primer Apellido')),
                ('segundoApellido', models.CharField(max_length=80, null=True, verbose_name='Segundo Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cédula de Extranjeria'), ('PA', 'Pasaaporte'), ('TI', 'Tarjeta de Identidad')], max_length=2, null=True, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=11, null=True, verbose_name='Numero de Documento')),
                ('telefono', models.CharField(max_length=80, null=True, verbose_name='telefono de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('fechaNacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('activo', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TC', 'Tarjeta de credito')], max_length=2)),
                ('banco', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'mediosDePago',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin Titulo', max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=21)),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=21)),
                ('imgPath', models.ImageField(default=None, upload_to='')),
                ('complemento', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Departamento')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Municipio')),
            ],
            options={
                'verbose_name_plural': 'ubicaciones',
            },
        ),
    ]
