# Generated by Django 2.0.1 on 2018-02-04 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(max_length=80, verbose_name='Nombres')),
                ('primerApellido', models.TextField(max_length=80, verbose_name='Primer Apellido')),
                ('segundoApellido', models.TextField(max_length=80, verbose_name='Segundo Apellido')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cédula de Extranjeria'), ('PA', 'Pasaaporte'), ('TI', 'Tarjeta de Identidad')], max_length=2, verbose_name='Tipo de Documento')),
                ('numeroDocumento', models.CharField(max_length=11, verbose_name='Numero de Documento')),
                ('telefono', models.TextField(max_length=80, verbose_name='telefono de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='MediosDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TC', 'Tarjeta de credito')], max_length=2)),
                ('franquicia', models.CharField(choices=[('FMC', 'MASTER CARD'), ('FAE', 'AMERICAN EXPRESS'), ('FVI', 'VISA'), ('FDC', 'DINNERS CLUB')], max_length=3)),
                ('banco', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=30)),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
                ('imgPath', models.ImageField(upload_to='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
            ],
        ),
    ]
