# Generated by Django 2.0.1 on 2018-02-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediosDePago',
            new_name='MedioDePago',
        ),
        migrations.RenameModel(
            old_name='Ubicaciones',
            new_name='Ubicacion',
        ),
    ]
