# Generated by Django 2.0.1 on 2018-02-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180204_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediodepago',
            options={'verbose_name_plural': 'mediosDePago'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name_plural': 'ubicaciones'},
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='title',
            field=models.CharField(default='Sin Titulo', max_length=30),
        ),
    ]
