# Generated by Django 2.0.1 on 2018-07-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180419_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagePath',
            field=models.FileField(null=True, upload_to='media/clientes'),
        ),
    ]
