# Generated by Django 2.0.1 on 2018-02-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_auto_20180204_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(null = True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=80, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primerApellido',
            field=models.CharField(max_length=80, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segundoApellido',
            field=models.CharField(max_length=80, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=80, verbose_name='telefono de contacto'),
        ),
    ]
