# Generated by Django 2.0.1 on 2018-02-12 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20180207_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=80, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeroDocumento',
            field=models.CharField(max_length=11, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primerApellido',
            field=models.CharField(max_length=80, null=True, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segundoApellido',
            field=models.CharField(max_length=80, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=80, null=True, verbose_name='telefono de contacto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('CE', 'Cédula de Extranjeria'), ('PA', 'Pasaaporte'), ('TI', 'Tarjeta de Identidad')], max_length=2, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
