# Generated by Django 2.0.1 on 2018-07-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_bolsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsa',
            name='estado',
        ),
    ]
