# Generated by Django 2.0.1 on 2018-07-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0030_auto_20180710_1453'),
        ('clientes', '0007_remove_bolsa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsa',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bolsaCompra', to='servicios.Compra'),
        ),
    ]
