# Generated by Django 2.0.1 on 2018-03-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20180227_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='clientes.Cliente'),
        ),
    ]
