# Generated by Django 2.0.1 on 2018-07-16 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_bolsa_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='clientes.Cliente'),
        ),
    ]
