# Generated by Django 2.0.1 on 2018-03-01 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20180301_1051'),
        ('parametrizacion', '0002_estadosesion_franquiciastarjetascredito_sexo_tipodocumento'),
        ('clientes', '0009_auto_20180301_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Cliente')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.Compra')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.EstadoSesion')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Ubicacion')),
            ],
            options={
                'verbose_name_plural': 'sesiones',
            },
        ),
    ]
