# Generated by Django 2.0.1 on 2018-08-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0003_auto_20180828_1413'),
        ('clientes', '0010_auto_20180716_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estadoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='estadoCliente', to='parametrizacion.EstadoCliente'),
        ),
    ]
