# Generated by Django 2.0.1 on 2018-03-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='franquicia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.FranquiciasTarjetasCredito'),
        ),
    ]
