# Generated by Django 2.0.1 on 2018-03-02 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0003_tipomediopago'),
        ('clientes', '0011_auto_20180302_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Sexo'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='departamento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='municipio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Municipio'),
            preserve_default=False,
        ),
    ]
