# Generated by Django 2.0.1 on 2018-03-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20180302_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Departamento'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parametrizacion.Municipio'),
        ),
    ]
