# Generated by Django 2.0.1 on 2018-09-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20180828_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='idFb',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
