# Generated by Django 2.0.1 on 2018-03-02 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20180302_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={},
        ),
        migrations.AddField(
            model_name='cliente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='modified',
            field=models.DateTimeField(auto_now=True,default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mediodepago',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediodepago',
            name='modified',
            field=models.DateTimeField(auto_now=True,default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sesion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='modified',
            field=models.DateTimeField(auto_now=True,default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='modified',
            field=models.DateTimeField(auto_now=True,default=django.utils.timezone.now),
        ),
    ]
