# Generated by Django 2.0.1 on 2018-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cliente_idfb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idFb',
            field=models.IntegerField(default=None),
        ),
    ]
