# Generated by Django 2.0.1 on 2018-09-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_auto_20180907_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idFb',
            field=models.CharField(max_length=80, null=True, verbose_name='idFb'),
        ),
    ]
