# Generated by Django 2.0.1 on 2018-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20180907_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='idGoog',
            field=models.CharField(max_length=80, null=True, verbose_name='idGoog'),
        ),
    ]
