# Generated by Django 2.0.1 on 2018-03-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20180312_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='complemento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
