# Generated by Django 2.0.1 on 2018-03-15 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_auto_20180313_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medio_de_pago', to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='mediodepago',
            name='franquicia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medio_de_pago', to='parametrizacion.FranquiciasTarjetasCredito'),
        ),
    ]
