# Generated by Django 2.0.1 on 2018-04-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('payU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrotarjetadecredito',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.Compra'),
        ),
        migrations.AddField(
            model_name='cobrotarjetadecredito',
            name='creditCardToken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payU.TarjetaDeCredito'),
        ),
    ]
