# Generated by Django 2.0.1 on 2018-02-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payU', '0002_auto_20180419_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobrotarjetadecredito',
            old_name='trnsancion',
            new_name='transancion',
        ),
        migrations.AddField(
            model_name='cobrotarjetadecredito',
            name='datos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
