# Generated by Django 2.0.1 on 2018-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payU', '0002_auto_20180331_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrotarjetadecredito',
            name='referenceCode',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
