# Generated by Django 2.0.1 on 2018-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payU', '0003_auto_20180401_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrotarjetadecredito',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cobrotarjetadecredito',
            name='referenceCode',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
