# Generated by Django 2.0.1 on 2018-04-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payU', '0004_auto_20180401_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobrotarjetadecredito',
            name='id',
        ),
        migrations.AlterField(
            model_name='cobrotarjetadecredito',
            name='referenceCode',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
