# Generated by Django 2.0.1 on 2018-04-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payU', '0005_auto_20180401_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetadecredito',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarjetadecredito',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
