# Generated by Django 2.0.1 on 2018-04-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payU', '0006_auto_20180403_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetadecredito',
            name='principal',
            field=models.BooleanField(),
        ),
    ]
