# Generated by Django 2.0.1 on 2018-04-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payU', '0009_auto_20180403_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetadecredito',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
