# Generated by Django 2.0.1 on 2018-03-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FranquiciasTarjetasCredito',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('franquicia', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
