# Generated by Django 2.0.1 on 2018-08-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0002_estadocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocliente',
            name='estado',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
