# Generated by Django 2.0.1 on 2018-03-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0002_estadosesion_franquiciastarjetascredito_sexo_tipodocumento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMedioPago',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('medioPago', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
