# Generated by Django 2.0.1 on 2018-08-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20180828_1432'),
        ('parametrizacion', '0003_auto_20180828_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoCliente',
        ),
    ]
